http:
  routers:
    syncthing:
      rule: Host(`sync.example.com`)
      entryPoints:
        - websecure
      service: syncthing
      tls:
        certResolver: letsencrypt
  services:
    syncthing:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:8384
